version: '3'

services:
  mysql:
    image: 'bitnami/mysql:latest'
    container_name: db
    environment:
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=docker
      - MYSQL_DATABASE=hfa
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306:3306
  app:
    depends_on:
      - mysql
    image: node:latest
    restart: always
    container_name: api
    ports:
      - '3333:3333'
    volumes:
      - .:/usr/app
    working_dir: /usr/app
    command: >
      bash -c "yarn migration && yarn dev:server"
